/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as UserRouteImport } from './routes/user/route'
import { Route as IndexImport } from './routes/index'
import { Route as UserSettingsImport } from './routes/user/settings'
import { Route as UserReportsImport } from './routes/user/reports'
import { Route as UserGenerateImport } from './routes/user/generate'
import { Route as UserDashboardImport } from './routes/user/dashboard'
import { Route as UserAnalyticsImport } from './routes/user/analytics'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const UserRouteRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserSettingsRoute = UserSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => UserRouteRoute,
} as any)

const UserReportsRoute = UserReportsImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => UserRouteRoute,
} as any)

const UserGenerateRoute = UserGenerateImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => UserRouteRoute,
} as any)

const UserDashboardRoute = UserDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => UserRouteRoute,
} as any)

const UserAnalyticsRoute = UserAnalyticsImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => UserRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/user/analytics': {
      id: '/user/analytics'
      path: '/analytics'
      fullPath: '/user/analytics'
      preLoaderRoute: typeof UserAnalyticsImport
      parentRoute: typeof UserRouteImport
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardImport
      parentRoute: typeof UserRouteImport
    }
    '/user/generate': {
      id: '/user/generate'
      path: '/generate'
      fullPath: '/user/generate'
      preLoaderRoute: typeof UserGenerateImport
      parentRoute: typeof UserRouteImport
    }
    '/user/reports': {
      id: '/user/reports'
      path: '/reports'
      fullPath: '/user/reports'
      preLoaderRoute: typeof UserReportsImport
      parentRoute: typeof UserRouteImport
    }
    '/user/settings': {
      id: '/user/settings'
      path: '/settings'
      fullPath: '/user/settings'
      preLoaderRoute: typeof UserSettingsImport
      parentRoute: typeof UserRouteImport
    }
  }
}

// Create and export the route tree

interface UserRouteRouteChildren {
  UserAnalyticsRoute: typeof UserAnalyticsRoute
  UserDashboardRoute: typeof UserDashboardRoute
  UserGenerateRoute: typeof UserGenerateRoute
  UserReportsRoute: typeof UserReportsRoute
  UserSettingsRoute: typeof UserSettingsRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserAnalyticsRoute: UserAnalyticsRoute,
  UserDashboardRoute: UserDashboardRoute,
  UserGenerateRoute: UserGenerateRoute,
  UserReportsRoute: UserReportsRoute,
  UserSettingsRoute: UserSettingsRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/user': typeof UserRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/user/analytics': typeof UserAnalyticsRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/generate': typeof UserGenerateRoute
  '/user/reports': typeof UserReportsRoute
  '/user/settings': typeof UserSettingsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/user': typeof UserRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/user/analytics': typeof UserAnalyticsRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/generate': typeof UserGenerateRoute
  '/user/reports': typeof UserReportsRoute
  '/user/settings': typeof UserSettingsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/user': typeof UserRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/user/analytics': typeof UserAnalyticsRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/generate': typeof UserGenerateRoute
  '/user/reports': typeof UserReportsRoute
  '/user/settings': typeof UserSettingsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/user'
    | '/login'
    | '/user/analytics'
    | '/user/dashboard'
    | '/user/generate'
    | '/user/reports'
    | '/user/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/user'
    | '/login'
    | '/user/analytics'
    | '/user/dashboard'
    | '/user/generate'
    | '/user/reports'
    | '/user/settings'
  id:
    | '__root__'
    | '/'
    | '/user'
    | '/login'
    | '/user/analytics'
    | '/user/dashboard'
    | '/user/generate'
    | '/user/reports'
    | '/user/settings'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserRouteRoute: typeof UserRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserRouteRoute: UserRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/user",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/user": {
      "filePath": "user/route.tsx",
      "children": [
        "/user/analytics",
        "/user/dashboard",
        "/user/generate",
        "/user/reports",
        "/user/settings"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/user/analytics": {
      "filePath": "user/analytics.tsx",
      "parent": "/user"
    },
    "/user/dashboard": {
      "filePath": "user/dashboard.tsx",
      "parent": "/user"
    },
    "/user/generate": {
      "filePath": "user/generate.tsx",
      "parent": "/user"
    },
    "/user/reports": {
      "filePath": "user/reports.tsx",
      "parent": "/user"
    },
    "/user/settings": {
      "filePath": "user/settings.tsx",
      "parent": "/user"
    }
  }
}
ROUTE_MANIFEST_END */
